export { Preloader, Search } from './common'
export { default as Header } from './header/header'
export { default as Movies } from './movies/movies'
export { default as PromoMovie } from './promoMovie/promoMovie'
export { default as Pagination } from './pagination/pagination'
